name: Build and Release

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install customtkinter reportlab pyinstaller

    - name: Build with PyInstaller
      run: |
        # Esto crea el ejecutable. Asegúrate que albion_cargo_app.py sea el nombre de tu archivo.
        pyinstaller --onefile --noconsole albion_cargo_app.py

    - name: Upload Executable
      uses: actions/upload-artifact@v4
      with:
        name: Albion-Cargo-App-Executable
        path: dist/
