name: Build and Release

on:
  push:
    branches:
      - main  # Esto le dice a GitHub que se ejecute cuando subas cambios a la rama 'main'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install customtkinter reportlab pyinstaller
        
    - name: Build with PyInstaller
      run: |
        pyinstaller --onefile albion_cargo_app.py
        - name: Upload Executable
      uses: actions/upload-artifact@v4
      with:
        name: Albion-Cargo-App
        path: dist/albion_cargo_app  # O el nombre exacto de tu ejecutable en la carpeta dist
